### ISSUE TITLE
PlatformIO CI: Github Actions: "sh: 1: Syntax error: "(" unexpected"

### ISSUE THREAD

**Issue by happyme531** [platformio/platformio-core#3761]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Description of problem

A project that successfully build on my windows 10 computer failed at the github actions.

#### Steps to Reproduce

see below

### Actual Results
```

Building in release mode
Compiling .pio/build/ttgo-t-watch/src/configmanager.cpp.o
sh: 1: Syntax error: "(" unexpected
*** [.pio/build/ttgo-t-watch/src/configmanager.cpp.o] Error 2
Compiling .pio/build/ttgo-t-watch/src/dm_specific.cpp.o
sh: 1: Syntax error: "(" unexpected
*** [.pio/build/ttgo-t-watch/src/dm_specific.cpp.o] Error 2
========================= [FAILED] Took 65.80 seconds =========================

```

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:ttgo-t-watch]
platform = espressif32
board = ttgo-t-watch
framework = arduino
board_build.f_flash = 80000000L
monitor_speed = 115200
upload_speed = 2000000
monitor_filters = 
	default
	esp32_exception_decoder
build_unflags = -std=gnu++11 -fno-rtti -Werror=reorder 
build_flags = 
	-std=gnu++2a	; c++2a->compiling error
	-Dtypeof(x)=decltype(x) 	; no longer useful
	-DCORE_DEBUG_LEVEL=4 
	-mfix-esp32-psram-cache-issue
build_type = release
lib_deps = 
	ESP Async WebServer
	xinyuan-lilygo/TTGO TWatch Library@^1.3.0
	bodmer/TFT_eSPI@^2.2.21
	aharshac/EasyNTPClient@^1.1.0
	ricmoo/QRCode@^0.0.1
src_filter = +<*> -<.git/> -<cparse/test-shunting-yard.cpp>
platform_packages = 
	toolchain-xtensa32 @ 2.80200.200827
	framework-arduinoespressif32 @ http://github.com/espressif/arduino-esp32.git#idf-release/v4.2
```

**Github Action Configuration**
```yaml

name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run

```
(ps:this is basically the example configuration provided in document.)
